// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260222132346_InitialSchemaVietnamese")]
    partial class InitialSchemaVietnamese
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValues")
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("old_values");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("user_agent");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("audit_logs");
                });

            modelBuilder.Entity("backend.Models.BlockedIp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BlockedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("blocked_at");

                    b.Property<long?>("BlockedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("blocked_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("reason");

                    b.HasKey("Id");

                    b.ToTable("blocked_ips");
                });

            modelBuilder.Entity("backend.Models.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TOA_NHA_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("DIA_CHI");

                    b.Property<string>("BuildingName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TEN_TOA_NHA");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("MO_TA");

                    b.Property<int>("NumberOfFloors")
                        .HasColumnType("int")
                        .HasColumnName("SO_TANG");

                    b.HasKey("Id");

                    b.HasIndex("BuildingName")
                        .IsUnique();

                    b.ToTable("TOA_NHA");
                });

            modelBuilder.Entity("backend.Models.ChiSoDien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CHI_SO_DIEN_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("MeterImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ANH_DONG_HO_URL");

                    b.Property<byte>("Month")
                        .HasColumnType("tinyint")
                        .HasColumnName("KY_THANG");

                    b.Property<decimal>("NewReading")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("CHI_SO_MOI");

                    b.Property<long>("ServiceUsageDetailId")
                        .HasColumnType("bigint")
                        .HasColumnName("CT_SDDV_ID");

                    b.Property<short>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("KY_NAM");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ServiceUsageDetailId", "Month", "Year")
                        .IsUnique();

                    b.ToTable("CHI_SO_DIEN");
                });

            modelBuilder.Entity("backend.Models.ChiSoNuoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CHI_SO_NUOC_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("MeterImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ANH_DONG_HO_URL");

                    b.Property<byte>("Month")
                        .HasColumnType("tinyint")
                        .HasColumnName("KY_THANG");

                    b.Property<decimal>("NewReading")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("CHI_SO_MOI");

                    b.Property<long>("ServiceUsageDetailId")
                        .HasColumnType("bigint")
                        .HasColumnName("CT_SDDV_ID");

                    b.Property<short>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("KY_NAM");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ServiceUsageDetailId", "Month", "Year")
                        .IsUnique();

                    b.ToTable("CHI_SO_NUOC");
                });

            modelBuilder.Entity("backend.Models.ChiTietHoaDon", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("CHI_TIET_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MO_TA");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("HOA_DON_ID");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LOAI_KHOAN");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SO_LUONG");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("DICH_VU_ID");

                    b.Property<long?>("ServiceUsageDetailId")
                        .HasColumnType("bigint")
                        .HasColumnName("CT_SDDV_ID");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DON_GIA");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("ServiceUsageDetailId");

                    b.ToTable("CHI_TIET_HOA_DON");
                });

            modelBuilder.Entity("backend.Models.ChiTietO", b =>
                {
                    b.Property<int>("ContractId")
                        .HasColumnType("int")
                        .HasColumnName("HOP_DONG_ID");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int")
                        .HasColumnName("CU_DAN_ID");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("TU_NGAY");

                    b.Property<string>("ResidencyRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("VAI_TRO_O");

                    b.Property<DateTime?>("ToDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DEN_NGAY");

                    b.HasKey("ContractId", "ResidentId");

                    b.HasIndex("ResidentId");

                    b.ToTable("CHI_TIET_O");
                });

            modelBuilder.Entity("backend.Models.ChiTietPhieuTatToan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("CHI_TIET_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SO_TIEN");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MO_TA");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LOAI_KHOAN");

                    b.Property<int>("SettlementId")
                        .HasColumnType("int")
                        .HasColumnName("TAT_TOAN_ID");

                    b.HasKey("Id");

                    b.HasIndex("SettlementId");

                    b.ToTable("CHI_TIET_PHIEU_TAT_TOAN");
                });

            modelBuilder.Entity("backend.Models.ChiTietSuDungDichVu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("CT_SDDV_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ApplyFrom")
                        .HasColumnType("datetime2")
                        .HasColumnName("AP_DUNG_TU");

                    b.Property<DateTime?>("ApplyTo")
                        .HasColumnType("datetime2")
                        .HasColumnName("AP_DUNG_DEN");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("GHI_CHU");

                    b.Property<decimal?>("OverrideUnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("OVERRIDE_DON_GIA");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("SO_LUONG");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int")
                        .HasColumnName("CU_DAN_ID");

                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("PHONG_ID");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("DICH_VU_ID");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int")
                        .HasColumnName("XE_ID");

                    b.HasKey("Id");

                    b.HasIndex("ResidentId");

                    b.HasIndex("RoomId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("VehicleId");

                    b.ToTable("CHI_TIET_SU_DUNG_DICH_VU");
                });

            modelBuilder.Entity("backend.Models.ChiTietTaiSanPhong", b =>
                {
                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("PHONG_ID");

                    b.Property<int>("AssetId")
                        .HasColumnType("int")
                        .HasColumnName("TAI_SAN_ID");

                    b.Property<string>("Condition")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TINH_TRANG");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("GHI_CHU");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("SO_LUONG");

                    b.HasKey("RoomId", "AssetId");

                    b.HasIndex("AssetId");

                    b.ToTable("CHI_TIET_TAI_SAN_PHONG");
                });

            modelBuilder.Entity("backend.Models.Floor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TANG_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("int")
                        .HasColumnName("TOA_NHA_ID");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("int")
                        .HasColumnName("SO_TANG");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId", "FloorNumber")
                        .IsUnique();

                    b.ToTable("TANG");
                });

            modelBuilder.Entity("backend.Models.HoaDon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HOA_DON_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContractId")
                        .HasColumnType("int")
                        .HasColumnName("HOP_DONG_ID");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DUE_DATE");

                    b.Property<byte>("Month")
                        .HasColumnType("tinyint")
                        .HasColumnName("THANG");

                    b.Property<string>("QrCodeUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("QR_CODE_URL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRANG_THAI");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TONG_TIEN");

                    b.Property<short>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("NAM");

                    b.HasKey("Id");

                    b.HasIndex("ContractId", "Month", "Year")
                        .IsUnique();

                    b.ToTable("HOA_DON");
                });

            modelBuilder.Entity("backend.Models.HopDong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HOP_DONG_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ActualRentPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("GIA_THUE_THUC_TE");

                    b.Property<decimal?>("DepositAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TIEN_COC");

                    b.Property<DateTime?>("ExpectedEndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("NGAY_KET_THUC_DU_KIEN");

                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("PHONG_ID");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("NGAY_BAT_DAU");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("HOP_DONG");
                });

            modelBuilder.Entity("backend.Models.KnowledgeBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KB_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("THE_LOAI");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOI_DUNG");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("TAGS");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("TIEU_DE");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATED_AT");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("UPDATED_BY");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("KNOWLEDGE_BASE");
                });

            modelBuilder.Entity("backend.Models.LichSuChat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("CHAT_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("MessageRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MESSAGE_ROLE");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MESSAGE_TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LICH_SU_CHAT");
                });

            modelBuilder.Entity("backend.Models.NhatKyNhacNo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("NHAC_NO_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("NOI_DUNG");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ERROR_MESSAGE");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("HOA_DON_ID");

                    b.Property<int>("ReminderCount")
                        .HasColumnType("int")
                        .HasColumnName("LAN_NHAC");

                    b.Property<string>("ReminderMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HINH_THUC");

                    b.Property<DateTime>("ReminderTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("NHAC_LUC");

                    b.Property<string>("SendStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRANG_THAI_GUI");

                    b.Property<int?>("SentByUserId")
                        .HasColumnType("int")
                        .HasColumnName("SENT_BY_USER_ID");

                    b.Property<int>("SentToUserId")
                        .HasColumnType("int")
                        .HasColumnName("SENT_TO_USER_ID");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("SentByUserId");

                    b.HasIndex("SentToUserId");

                    b.ToTable("NHAT_KY_NHAC_NO");
                });

            modelBuilder.Entity("backend.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("is_read");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("link_url");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("notification_type");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("priority");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("read_at");

                    b.Property<int?>("RecipientId")
                        .HasColumnType("int")
                        .HasColumnName("recipient_id");

                    b.Property<int?>("RelatedId")
                        .HasColumnType("int")
                        .HasColumnName("related_id");

                    b.Property<int?>("ScopeId")
                        .HasColumnType("int")
                        .HasColumnName("scope_id");

                    b.Property<string>("ScopeType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("scope_type");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("sent_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("backend.Models.Resident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CU_DAN_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("HO_TEN");

                    b.Property<string>("Hometown")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("QUE_QUAN");

                    b.Property<string>("IdCardBackUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("CCCD_BACK_URL");

                    b.Property<string>("IdCardFrontUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("CCCD_FRONT_URL");

                    b.Property<string>("IdCardNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("SO_CCCD");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("SO_DIEN_THOAI");

                    b.HasKey("Id");

                    b.HasIndex("IdCardNumber")
                        .IsUnique()
                        .HasFilter("[SO_CCCD] IS NOT NULL");

                    b.ToTable("CU_DAN");
                });

            modelBuilder.Entity("backend.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PHONG_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Area")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("DIEN_TICH");

                    b.Property<decimal?>("DefaultRentPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DON_GIA_THUE_MAC_DINH");

                    b.Property<int>("FloorId")
                        .HasColumnType("int")
                        .HasColumnName("TANG_ID");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MA_PHONG");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRANG_THAI");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.HasIndex("RoomCode")
                        .IsUnique();

                    b.ToTable("PHONG");
                });

            modelBuilder.Entity("backend.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DICH_VU_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CommonUnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DON_GIA_CHUNG");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TEN_DICH_VU");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LOAI");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DON_VI");

                    b.HasKey("Id");

                    b.ToTable("DICH_VU");
                });

            modelBuilder.Entity("backend.Models.TaiSan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TAI_SAN_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MA_TAI_SAN");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TEN_TAI_SAN");

                    b.HasKey("Id");

                    b.HasIndex("AssetCode")
                        .IsUnique();

                    b.ToTable("TAI_SAN");
                });

            modelBuilder.Entity("backend.Models.TatToan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TAT_TOAN_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContractId")
                        .HasColumnType("int")
                        .HasColumnName("HOP_DONG_ID");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("GHI_CHU");

                    b.Property<string>("PdfUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("PDF_URL");

                    b.Property<DateTime>("SettlementDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("NGAY_TAT_TOAN");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TONG_CONG");

                    b.HasKey("Id");

                    b.HasIndex("ContractId")
                        .IsUnique();

                    b.ToTable("TAT_TOAN");
                });

            modelBuilder.Entity("backend.Models.ThanhToan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("THANH_TOAN_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SO_TIEN");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("HOA_DON_ID");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("PAID_AT");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LOAI");

                    b.Property<int?>("SettlementId")
                        .HasColumnType("int")
                        .HasColumnName("TAT_TOAN_ID");

                    b.Property<string>("TransactionCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MA_GIAO_DICH");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("SettlementId");

                    b.ToTable("THANH_TOAN", t =>
                        {
                            t.HasCheckConstraint("CHK_THANH_TOAN_REF", "([HOA_DON_ID] IS NOT NULL AND [TAT_TOAN_ID] IS NULL) OR ([HOA_DON_ID] IS NULL AND [TAT_TOAN_ID] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("USER_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit")
                        .HasColumnName("IS_LOCKED");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("LAST_LOGIN_AT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MAT_KHAU_HASH");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("SO_DIEN_THOAI");

                    b.Property<int?>("ResidentId")
                        .HasColumnType("int")
                        .HasColumnName("CU_DAN_ID");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("VAI_TRO");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("ResidentId");

                    b.ToTable("USER");
                });

            modelBuilder.Entity("backend.Models.UserSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("device_info");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("revoked_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_sessions");
                });

            modelBuilder.Entity("backend.Models.Xe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("XE_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CancellationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("NGAY_HUY");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("BIEN_SO");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("NGAY_DANG_KY");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int")
                        .HasColumnName("CU_DAN_ID");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LOAI_XE");

                    b.HasKey("Id");

                    b.HasIndex("LicensePlate")
                        .IsUnique();

                    b.HasIndex("ResidentId");

                    b.ToTable("XE");
                });

            modelBuilder.Entity("backend.Models.YeuCauSuaChua", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("YEU_CAU_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("GHI_CHU_ADMIN");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CLOSED_AT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("MO_TA");

                    b.Property<string>("IssueType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LOAI_SU_CO");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MEDIA_URL");

                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("PHONG_ID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRANG_THAI");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("YEU_CAU_SUA_CHUA");
                });

            modelBuilder.Entity("backend.Models.AuditLog", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.ChiSoDien", b =>
                {
                    b.HasOne("backend.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Models.ChiTietSuDungDichVu", "ServiceUsageDetail")
                        .WithMany("ChiSoDiens")
                        .HasForeignKey("ServiceUsageDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("ServiceUsageDetail");
                });

            modelBuilder.Entity("backend.Models.ChiSoNuoc", b =>
                {
                    b.HasOne("backend.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Models.ChiTietSuDungDichVu", "ServiceUsageDetail")
                        .WithMany("ChiSoNuocs")
                        .HasForeignKey("ServiceUsageDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("ServiceUsageDetail");
                });

            modelBuilder.Entity("backend.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("backend.Models.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Service", "Service")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("backend.Models.ChiTietSuDungDichVu", "ServiceUsageDetail")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("ServiceUsageDetailId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("HoaDon");

                    b.Navigation("Service");

                    b.Navigation("ServiceUsageDetail");
                });

            modelBuilder.Entity("backend.Models.ChiTietO", b =>
                {
                    b.HasOne("backend.Models.HopDong", "HopDong")
                        .WithMany("ChiTietOs")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Resident", "Resident")
                        .WithMany("ChiTietOs")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HopDong");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("backend.Models.ChiTietPhieuTatToan", b =>
                {
                    b.HasOne("backend.Models.TatToan", "TatToan")
                        .WithMany("ChiTietPhieuTatToans")
                        .HasForeignKey("SettlementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TatToan");
                });

            modelBuilder.Entity("backend.Models.ChiTietSuDungDichVu", b =>
                {
                    b.HasOne("backend.Models.Resident", "Resident")
                        .WithMany("ChiTietSuDungDichVus")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Room", "Room")
                        .WithMany("ChiTietSuDungDichVus")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("backend.Models.Service", "Service")
                        .WithMany("ChiTietSuDungDichVus")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Xe", "Vehicle")
                        .WithMany("ChiTietSuDungDichVus")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Resident");

                    b.Navigation("Room");

                    b.Navigation("Service");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("backend.Models.ChiTietTaiSanPhong", b =>
                {
                    b.HasOne("backend.Models.TaiSan", "TaiSan")
                        .WithMany("ChiTietTaiSanPhongs")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Room", "Room")
                        .WithMany("ChiTietTaiSanPhongs")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("TaiSan");
                });

            modelBuilder.Entity("backend.Models.Floor", b =>
                {
                    b.HasOne("backend.Models.Building", "Building")
                        .WithMany("Floors")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("backend.Models.HoaDon", b =>
                {
                    b.HasOne("backend.Models.HopDong", "HopDong")
                        .WithMany("HoaDons")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HopDong");
                });

            modelBuilder.Entity("backend.Models.HopDong", b =>
                {
                    b.HasOne("backend.Models.Room", "Room")
                        .WithMany("HopDongs")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("backend.Models.KnowledgeBase", b =>
                {
                    b.HasOne("backend.Models.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("backend.Models.LichSuChat", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithMany("LichSuChats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.NhatKyNhacNo", b =>
                {
                    b.HasOne("backend.Models.HoaDon", "HoaDon")
                        .WithMany("NhatKyNhacNos")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User", "SentByUser")
                        .WithMany("NhatKyNhacNosSentBy")
                        .HasForeignKey("SentByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("backend.Models.User", "SentToUser")
                        .WithMany("NhatKyNhacNosSentTo")
                        .HasForeignKey("SentToUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("SentByUser");

                    b.Navigation("SentToUser");
                });

            modelBuilder.Entity("backend.Models.Notification", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Room", b =>
                {
                    b.HasOne("backend.Models.Floor", "Floor")
                        .WithMany("Rooms")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("backend.Models.TatToan", b =>
                {
                    b.HasOne("backend.Models.HopDong", "HopDong")
                        .WithOne("TatToan")
                        .HasForeignKey("backend.Models.TatToan", "ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HopDong");
                });

            modelBuilder.Entity("backend.Models.ThanhToan", b =>
                {
                    b.HasOne("backend.Models.HoaDon", "HoaDon")
                        .WithMany("ThanhToans")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("backend.Models.TatToan", "TatToan")
                        .WithMany("ThanhToans")
                        .HasForeignKey("SettlementId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("HoaDon");

                    b.Navigation("TatToan");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.HasOne("backend.Models.Resident", "Resident")
                        .WithMany("Users")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("backend.Models.UserSession", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Xe", b =>
                {
                    b.HasOne("backend.Models.Resident", "Resident")
                        .WithMany("Xes")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("backend.Models.YeuCauSuaChua", b =>
                {
                    b.HasOne("backend.Models.Room", "Room")
                        .WithMany("YeuCauSuaChuas")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User", "User")
                        .WithMany("YeuCauSuaChuas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Building", b =>
                {
                    b.Navigation("Floors");
                });

            modelBuilder.Entity("backend.Models.ChiTietSuDungDichVu", b =>
                {
                    b.Navigation("ChiSoDiens");

                    b.Navigation("ChiSoNuocs");

                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("backend.Models.Floor", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("backend.Models.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");

                    b.Navigation("NhatKyNhacNos");

                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("backend.Models.HopDong", b =>
                {
                    b.Navigation("ChiTietOs");

                    b.Navigation("HoaDons");

                    b.Navigation("TatToan");
                });

            modelBuilder.Entity("backend.Models.Resident", b =>
                {
                    b.Navigation("ChiTietOs");

                    b.Navigation("ChiTietSuDungDichVus");

                    b.Navigation("Users");

                    b.Navigation("Xes");
                });

            modelBuilder.Entity("backend.Models.Room", b =>
                {
                    b.Navigation("ChiTietSuDungDichVus");

                    b.Navigation("ChiTietTaiSanPhongs");

                    b.Navigation("HopDongs");

                    b.Navigation("YeuCauSuaChuas");
                });

            modelBuilder.Entity("backend.Models.Service", b =>
                {
                    b.Navigation("ChiTietHoaDons");

                    b.Navigation("ChiTietSuDungDichVus");
                });

            modelBuilder.Entity("backend.Models.TaiSan", b =>
                {
                    b.Navigation("ChiTietTaiSanPhongs");
                });

            modelBuilder.Entity("backend.Models.TatToan", b =>
                {
                    b.Navigation("ChiTietPhieuTatToans");

                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Navigation("LichSuChats");

                    b.Navigation("NhatKyNhacNosSentBy");

                    b.Navigation("NhatKyNhacNosSentTo");

                    b.Navigation("YeuCauSuaChuas");
                });

            modelBuilder.Entity("backend.Models.Xe", b =>
                {
                    b.Navigation("ChiTietSuDungDichVus");
                });
#pragma warning restore 612, 618
        }
    }
}
